language: elixir
env:
  - MIX_ENV=test
matrix:
  include:
    - elixir: 1.5
      otp_release: 20.0
    - elixir: 1.6
      otp_release: 20.0
    - elixir: 1.6
      otp_release: 21.0
script: mix coveralls.travis
